services:
  rsshub:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-1200}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - letsencrypt-network

networks:
  letsencrypt-network:
    name: letsencrypt-network
    external: true