services:
  rsshub:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-1200}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - step-ca-network

networks:
  step-ca-network:
    name: step-ca-network
    external: true